FirstTask
Appolinariya1/TMS_AQA_Koval pull request #13
Opened 2024-02-06 21:14 UTC by Appolinariya1

ДЗ по теме N Unit

2024-02-12 20:54 UTC, wildpioneer requested changes

2024-02-12 20:54 UTC, wildpioneer commented on HomeWork_NUnit/Calculator.cs
> +        if (double.IsNaN(result) || double.IsInfinity(result))
Не нужно добавлять логику в сам метод - все эти моменты нужно проверить в тестах

2024-02-12 20:54 UTC, wildpioneer commented on HomeWork_NUnit/DivideTests.cs
> +            Calculator.Div(x, y);
Переделать с учетом исправления в самом методе

2024-02-12 20:54 UTC, wildpioneer commented on HomeWork_NUnit/DivideTests.cs
> +            Assert.Fail();
Аналогично

2024-02-24 14:11 UTC, Appolinariya1 commented on HomeWork_NUnit/Calculator.cs
> +        if (double.IsNaN(result) || double.IsInfinity(result))
Вынесла логику из метода в тесты.

2024-02-24 14:11 UTC, Appolinariya1 commented on HomeWork_NUnit/DivideTests.cs
> +            Calculator.Div(x, y);
Тут поправила

2024-02-24 14:12 UTC, Appolinariya1 commented on HomeWork_NUnit/DivideTests.cs
> +            Assert.Fail();
А вот тут не поняла, как сделать без проверки на исключение, ведь при делении целых на ноль оно будет. Поправила саму структуру немного.

2024-03-19 11:16 UTC, wildpioneer commented
Проверено

2024-03-19 11:16 UTC, closed without merging