Home work Selenium Basic
Appolinariya1/TMS_AQA_Koval pull request #14
Opened 2024-02-10 22:23 UTC by Appolinariya1

2024-02-12 20:56 UTC, wildpioneer requested changes

2024-02-12 20:56 UTC, wildpioneer commented on SeleniumBasic/Tests/HomeWork/HwSecondTask.cs
> +            Assert.That(laminateCountResult.Text.Replace("\r", ""),
А почему ты оставляешь \n в тексте?

2024-02-24 14:42 UTC, Appolinariya1 commented on SeleniumBasic/Tests/HomeWork/HwSecondTask.cs
> +            Assert.That(laminateCountResult.Text.Replace("\r", ""),
Потому что на этот символ тест не ругался) Но, вероятно, в других браузерах/системах могут быть проблемы со спецсимволами, поэтому убрала и \n тоже.

2024-03-19 11:18 UTC, wildpioneer commented
Проверено

2024-03-19 11:18 UTC, closed without merging