Home work types and operators
Appolinariya1/TMS_AQA_Koval pull request #2
Opened 2023-11-18 20:22 UTC by Appolinariya1

Добрый день! 
Сделано меню выбора задания при запуске программы. В четвертом задании сделала проверку числа двумя разными способами. Для заданий 1, 2, 4 переиспользуемую функцию получения числа из консоли вынесла в отдельный класс Helpers.

2023-11-19 21:25 UTC, wildpioneer requested changes

2023-11-19 21:25 UTC, wildpioneer commented on TypesAndOperators/FirstTask.cs
> +        switch (b)
Перед switch лучше добавлять пустую строку.

2023-11-19 21:25 UTC, wildpioneer commented on TypesAndOperators/FourthTask.cs
> +        return lastChar == '0' || lastChar == '2' || lastChar == '4' || lastChar == '6' || lastChar == '8';
Для целых чисел неплохой вариант - рабочий. Но все же не совсем тот,

2023-11-19 21:25 UTC, wildpioneer commented on TypesAndOperators/Helpers.cs
> +        if (!int.TryParse(inputString, out result))
По взрослому ;)

2023-11-19 21:25 UTC, wildpioneer commented on TypesAndOperators/Program.cs
> +int.TryParse(Console.ReadLine(), out var task);
А почему тут ты не хочешь воспользоваться своим методом GetNumberFromConsole?

2023-11-19 21:25 UTC, wildpioneer commented on TypesAndOperators/ThirdTask.cs
> +        var weatherDictionary = new Dictionary<string, string>()
Хитрим - мы типа коллекций вообще не знаем ;)

2023-11-19 22:06 UTC, Appolinariya1 commented on TypesAndOperators/Program.cs
> +int.TryParse(Console.ReadLine(), out var task);
Потому что долго делала дз и мозг к концу поплыл :)

2023-11-19 22:08 UTC, Appolinariya1 commented on TypesAndOperators/FourthTask.cs
> +        return lastChar == '0' || lastChar == '2' || lastChar == '4' || lastChar == '6' || lastChar == '8';
Согласно определению четность - характеристика целых чисел. А какой вариант лучше?

2023-11-19 22:11 UTC, Appolinariya1 commented on TypesAndOperators/ThirdTask.cs
> +        var weatherDictionary = new Dictionary<string, string>()
Вбила в гугл "словари с#", вышла на метанит и узнала про dictionary, поняла, что подойдет)

2023-11-27 08:54 UTC, wildpioneer commented on TypesAndOperators/FourthTask.cs
> +        return lastChar == '0' || lastChar == '2' || lastChar == '4' || lastChar == '6' || lastChar == '8';
Высылал в чате - с побитовым сдвигом

2023-11-27 08:55 UTC, closed without merging