Home work arrays
Appolinariya1/TMS_AQA_Koval pull request #3
Opened 2023-11-25 21:46 UTC by Appolinariya1

Задания 1 - 4, плюс меню выбора заданий

2023-11-27 13:43 UTC, wildpioneer requested changes

2023-11-27 13:43 UTC, wildpioneer commented on TypesAndOperators/FirstTask.cs
> +        if (numbers.Contains(inputNumber))
Перед IF нужна пустая строка

2023-11-27 13:43 UTC, wildpioneer commented on TypesAndOperators/FourthTask.cs
> +        for (int i = 0; i < numbers1.Length; i++)
Перед FOR нужна пустая строка

2023-11-27 13:43 UTC, wildpioneer commented on TypesAndOperators/FourthTask.cs
> +        switch ((aveNumber1, aveNumber2))
Интересная структура

2023-11-27 13:43 UTC, wildpioneer commented on TypesAndOperators/SecondTask.cs
> +
Желательно вывести массив - потому как не понятно - какие же цифры в нем есть - чтобы указать что надо удалять

2023-11-27 13:43 UTC, wildpioneer commented on TypesAndOperators/SecondTask.cs
> +                numbersFiltered[i - offset] = numbers[i];
Не понял данную строку - а почему просто не использовать numbersFiltered[offset] и именно здесь увеличивать offset на 1?

2023-11-27 13:43 UTC, wildpioneer commented on TypesAndOperators/ThirdTask.cs
> +        int[] numbers = new int [arraySize];
Нужно здесь сделать проверку что введено целое число > 0

2023-11-27 13:43 UTC, wildpioneer commented on TypesAndOperators/ThirdTask.cs
> +        if (arraySize == 0)
С учетом предыдущего замечания - эта проверка не нужна будет

2023-11-27 13:43 UTC, wildpioneer commented on TypesAndOperators/ThirdTask.cs
> +        Console.WriteLine($"Среднее значение из чисел массива = {aveNumber}");
Это будет среднее арифметическое - а надо просто среднее
"1 5 10" - среднее 5, а среднее арифметическое 5.3

2023-11-27 13:43 UTC, wildpioneer commented on TypesAndOperators/ThirdTask.cs
> +        for (int i = 1; i < numbers.Length; i++)
Максимальное и минимальное можно найти в едином проходе - не надо делать два цикла для этого

2023-11-27 17:12 UTC, Appolinariya1 commented on TypesAndOperators/ThirdTask.cs
> +        Console.WriteLine($"Среднее значение из чисел массива = {aveNumber}");
В этой задаче размер массива задается с консоли, соответственно, он может быть с четным количеством элементов. В случае, например "1, 5, 7, 10" мне надо будет вывести "5, 7" или "6" в качестве "среднего"? Или в случае четного количества вывести, что среднего нет?

2023-11-27 17:54 UTC, Appolinariya1 commented on TypesAndOperators/SecondTask.cs
> +
Исправила

2023-11-27 17:55 UTC, Appolinariya1 commented on TypesAndOperators/SecondTask.cs
> +                numbersFiltered[i - offset] = numbers[i];
Исправила

2024-01-29 09:41 UTC, wildpioneer commented
Проверено

2024-01-29 09:41 UTC, closed without merging